version: '3.3'
services:
  simulate:
    image: rustlang/rust:nightly-slim
    tty: true
    working_dir: /workspace
    volumes:
      - .registry_cache:/usr/local/cargo/registry:delegated
      - ./:/workspace
